### ISSUE TITLE
switch to next disk if disk is full

### ISSUE THREAD

**Issue by rsulym** [tobernguyen/madmax-manager#2]
Hi, disk6 is full, manager supposed to switch to next free drive, but it doesn't:
>>>
[P2] max_table_size = 4295038709
[P2] Table 7 scan took 20.4948 sec
[P2] Table 7 rewrite took 35.5026 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 50.877 sec
[P2] Table 6 rewrite took 615.978 sec, dropped 581384307 entries (13.5393 %)
[P2] Table 5 scan took 402.317 sec
Copy to /mnt/disk6/plots/plot-k32-2021-06-28-09-22-2c675be8bb120fd61e9c918cbe6d6ba7b5f0043087c1465dc4bab7c2bd3eae4f.plot failed with: fwrite() failed
[P2] Table 5 rewrite took 588.628 sec, dropped 762136583 entries (17.7464 %)
[P2] Table 4 scan took 457.432 sec
Copy to /mnt/disk6/plots/plot-k32-2021-06-28-09-22-2c675be8bb120fd61e9c918cbe6d6ba7b5f0043087c1465dc4bab7c2bd3eae4f.plot failed with: fwrite() failed
>>>

**Comment by tobernguyen** [comment]
> Hi, disk6 is full, manager supposed to switch to next free drive, but it doesn't:
> 
> > > >
> 
> [P2] max_table_size = 4295038709
> [P2] Table 7 scan took 20.4948 sec
> [P2] Table 7 rewrite took 35.5026 sec, dropped 0 entries (0 %)
> [P2] Table 6 scan took 50.877 sec
> [P2] Table 6 rewrite took 615.978 sec, dropped 581384307 entries (13.5393 %)
> [P2] Table 5 scan took 402.317 sec
> Copy to /mnt/disk6/plots/plot-k32-2021-06-28-09-22-2c675be8bb120fd61e9c918cbe6d6ba7b5f0043087c1465dc4bab7c2bd3eae4f.plot failed with: fwrite() failed
> [P2] Table 5 rewrite took 588.628 sec, dropped 762136583 entries (17.7464 %)
> [P2] Table 4 scan took 457.432 sec
> Copy to /mnt/disk6/plots/plot-k32-2021-06-28-09-22-2c675be8bb120fd61e9c918cbe6d6ba7b5f0043087c1465dc4bab7c2bd3eae4f.plot failed with: fwrite() failed
> 
> > > >

Did you copy more files to disk6 after the plotter has started? The manager only calculates the number of plots it can fit to the disk before instructing the plotter to craft the plots.

In short:
1. Before you run the plotter, let's say disk6 can fit 10 plots
2. The manager runs the madmax plotter with `-n 10` argument so that the plotter will craft 10 plots continuously (non-stop) to disk6
3. If during step 2, you did anything to disk6 make it couldn't hold 10 plots then the manager won't be able to instruct the plotter to copy the plot to another destination and the the madmax plotter will fail to copy plots like what you saw.

**Comment by rsulym** [comment]
@tobernguyen hi, thanks for reply, i totally understand your point but this was not my case, i did nothing with disk6. let me keep watching.

**Comment by tobernguyen** [comment]
> @tobernguyen hi, thanks for reply, i totally understand your point but this was not my case, i did nothing with disk6. let me keep watching.

Hi. I think I found the problem. This happens when there are multiple destination directories specified in the `config.ini`. I have fixed it. Can you try to update the latest version and let me know?

To update, go to the madmax-manager directory and do a `git pull`  then you should have the latest version.

**Comment by tobernguyen** [comment]
Close as fixed.
