### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by Saperlipopette01** [tobernguyen/madmax-manager#3]
Hello, with the new version of MADMAX chia plotter which contains the -c argument, when do you plan to modify the script? Thank you for your response .

Vincent   FRENCH FARMERS POOL :-)

**Comment by rsulym** [comment]
you can just change -p to -c key and key value and you're good to go

**Comment by tobernguyen** [comment]
I will look into this soon

**Comment by tobernguyen** [comment]
> Hello, with the new version of MADMAX chia plotter which contains the -c argument, when do you plan to modify the script? Thank you for your response .
> 
> Vincent FRENCH FARMERS POOL :-)

I just updated the code to support `-c` argument. Please pull the latest version of the manager and add a new config to your `config.ini`
```
pool_contract_address=""
```

I'm not sure if you can specify both `pool_public_key` and `pool_contract_address` but from MadMax's README, it said that you will want to specify `pool_contract_address` (`-c`) _instead of_ `pool_public_key` (`-p`). I haven't tested specifying both. Can you please let me know what happens when you specify both? Thanks.

**Comment by rsulym** [comment]
@tobernguyen it should be only one argument, -c or -p, not both together.

**Comment by tobernguyen** [comment]
Thanks @rsulym . I will add validation for that. Anyway, I just updated the code to remove the requirement of `pool_public_key` so the manager won't complain about `pool_public_key` not provided.

**Comment by tobernguyen** [comment]
@Saperlipopette01 Please pull the latest code again and let me know if you have any issues.

**Comment by tobernguyen** [comment]
Close for now as it has been resolved. Feel free to re-open if you still have the issue.
